:bug: Remove id attribute from city model as it doesn't have a primary key.
Fixes:
 > SequelizeDatabaseError: Invalid column name 'id'
on Cities table.

This is a Sequelize 6 workaround to tell Sequelize there is no primary key.
See https://sequelize.org/docs/v6/other-topics/legacy/#primary-keys